# Testing Neural Network

## Importing Required Library

In [ ]:
import torch
import torch.nn as nn
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.preprocessing import StandardScaler
import joblib

In [73]:
# defining model structure
class PredictRisk(nn.Module):
  def __init__(self, input_dim):
    super(PredictRisk, self).__init__()
    self.net = nn.Sequential(
        nn.Linear(input_dim,16),
        nn.ReLU(),
        nn.Dropout(p=0.4),

        nn.Linear(16,8),
        nn.ReLU(),
        nn.Dropout(p=0.4),

        nn.Linear(8,4),
        nn.ReLU(),
        nn.Dropout(p=0.4),

        nn.Linear(4,1),
        nn.Sigmoid()
    )

  def forward(self, x):
    return self.net(x)

In [88]:
import warnings
from sklearn.exceptions import InconsistentVersionWarning
warnings.filterwarnings("ignore", category=InconsistentVersionWarning)
model_path = "/home/ritu/safetronics/Neural Model/NeuralModel.pth"
scaler_path = "/home/ritu/safetronics/Neural Model/Neural_Scaler.joblib"
scaler = joblib.load(scaler_path)

In [89]:
input_dim = 9
model = PredictRisk(input_dim = input_dim)

In [90]:
# load the state dict
state = torch.load(model_path)
model.load_state_dict(state)
model.eval()

PredictRisk(
  (net): Sequential(
    (0): Linear(in_features=9, out_features=16, bias=True)
    (1): ReLU()
    (2): Dropout(p=0.4, inplace=False)
    (3): Linear(in_features=16, out_features=8, bias=True)
    (4): ReLU()
    (5): Dropout(p=0.4, inplace=False)
    (6): Linear(in_features=8, out_features=4, bias=True)
    (7): ReLU()
    (8): Dropout(p=0.4, inplace=False)
    (9): Linear(in_features=4, out_features=1, bias=True)
    (10): Sigmoid()
  )
)

In [99]:
dummy_raw = np.array([
                      [95,36.63303504742271,95.10907491408022,52,0,63.72917999036624,1.913939327813188,0.0510863832043346,17.397305807254117],
                      [60,37.0651073739614,99.02601660746126,51,0,81.05001704935856,1.8499982729357087,0.0527745613223041,23.68156855449996]
                      ])

In [100]:
dummy_scaled = scaler.transform(dummy_raw)

In [101]:
x = torch.tensor(dummy_scaled, dtype=torch.float32)

In [102]:
x

tensor([[ 1.3406, -0.2664, -1.6594, -0.0702, -0.9974, -0.7804,  1.1354, -1.6935,
         -1.1816],
        [-1.6896,  0.7304,  1.0559, -0.1183, -0.9974,  0.4169,  0.6930, -1.6349,
         -0.2069]])

In [103]:
with torch.no_grad():
    prob = model(x)
    prob = prob.numpy().ravel()
    pred_class = (prob > 0.5).astype(int)

In [104]:
prob

array([0.0151483, 0.702324 ], dtype=float32)

In [105]:
pred_class

array([0, 1])

In [108]:
print("Predicated Probability: ", prob[0],prob[1])
print("Predicated class: ", pred_class[0],pred_class[1])

Predicated Probability:  0.0151483035 0.702324
Predicated class:  0 1
